### ISSUE TITLE
VS Community installation exits with non-zero code: 1

### ISSUE THREAD

**Issue by timmkrause** [lukas-lansky/visual-studio-docker-build#1]
First: Thank you for providing your solution here, I really appreciate your work.

Using your approach as a starting point we want to run the container as an Azure Pipelines (Build) Agent, for this purpose we need to run

`RUN & "$env:TEMP\vs_community.exe" --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.Data --includeRecommended --includeOptional --quiet --wait --norestart --noUpdateInstaller | Out-Default`

But it seems to always exit with the following error:

`ERROR: Service 'azp-agent' failed to build: The command 'powershell & "$env:TEMP\vs_community.exe" --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.Data --includeRecommended --includeOptional --quiet --wait --norestart --noUpdateInstaller | Out-Default' returned a non-zero code: 1`

Also using your `Dockerfile` there seems to be a chance that `build`ing fails. Did you try it multiple times? Have you already experienced this behavior? Any ideas why this happens?

**NOTE:** In the 3rd try of building the image the installer went through successfully. But I am still interested in your experience with the approach.

**Comment by timmkrause** [comment]
Somehow it just works now... unfortunately I don't know why.

**Comment by zleight1** [comment]
At least I know I'm not crazy.... Same thing happens for me

> Somehow it just works now... unfortunately I don't know why.
